- name: demo on variables
  hosts: all
  vars:
      URL: play.google.com

  # vars_prompt:
  #     - name : URL
  #       prompt: Enter URL
  #       private: no
  tasks:
    - name: printing URL  
      ansible.builtin.debug:
        msg: Url that we print is {{ URL }}

    - name: printing URL with quotes
      ansible.builtin.debug:
      msg: "{{ URL }}"

    - name: printing URL from CLI
      ansible.builtin.debug:
      msg: URL_ CLI is {{ CLI_URL }}
 

    - name: Printing URL from CLI 
      ansible.builtin.debug:
        msg: URL_CLI is {{ CLI_URL }} 