- name: demo on variables
  hosts: all # all is default group in inventary file  which includes everything
  vars:
      URL: play.google.com
  tasks:
    - name: Printing  URL
      ansible.builtin.debug:
        msg: Url that we print id {{URL}} 

    - name: Printing URL with quotes 
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: task.google.com