- name: Installing Nginx
  ansible.builtin.package:
    name: nginx 
    state: present 

- name: Coping nginx config 
  ansible.builtin.template:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
  notify: Restarting Nginx Service 

- name: Starting Nginx Service 
  ansible.builtin.service:
    name: nginx 
    state: started
    enabled: yes

- name:  Download and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download-and-extract  

# Uncomment it only for downloading from Github
# - name: Cleanup of old html content 
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: Coping frotend context to nginx path 
#   ansible.builtin.copy:
#     src: /tmp/frontend-main/static/
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: Coping proxy config 
  ansible.builtin.template:
    src: roboshop.conf 
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restarting Nginx Service 

- name: Configuing rsyslog
  ansible.builtin.include_role:
    name: elk  
    tasks_from: rsyslog

- name: Installing Filebeat
  ansible.builtin.include_role:
    name: elk 
    tasks_from: filebeat 

- name: Install Node Exporter 
  ansible.builtin.shell: curl -s https://gitlab.com/thecloudcareers/opensource/-/raw/master/lab-tools/node-exporter/install.sh | bash

- name: Configuing system name 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname