- name: Installing Erlang Yum Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Configure RabbitMQ Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing RabbitMQ and Dependencies
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed 

- name: Starting {{COMPONENT}} Service 
  ansible.builtin.systemd:
    name: "{{COMPONENT}}-server" 
    state: started 
    enabled: yes

- name: Adding {{COMPONENT}} App User  
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Configuing system name 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname