- name: Creating application user
  ansible.builtin.user:
    name: "{{APPUSER}}" 
    comment: Roboshop Application User
  register: APPUSER_REGISTER

- name: Installing python boto modules
  ansible.builtin.pip:
    name:
      - boto3 
      - botocore
    executable: pip3  # Then installation will happen with pip3. If not, goes with python 2 by default.