- name: Coping systemd file 
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service 

# - name: Starting {{COMPONENT}} Service 
#   ansible.builtin.systemd:
#     name: "{{COMPONENT}}" 
#     state: restarted
#     enabled: yes
#     daemon_reload: yes

- name: Configuing the {{COMPONENT}} svc
  ansible.builtin.include_role:
    name: common 
    tasks_from: start-svc